// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	UserMapTable string
	UserTable    string
}{
	UserMapTable: "user_map_table",
	UserTable:    "user_table",
}
