// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("UserMapTables", testUserMapTables)
	t.Run("UserTables", testUserTables)
}

func TestDelete(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesDelete)
	t.Run("UserTables", testUserTablesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesQueryDeleteAll)
	t.Run("UserTables", testUserTablesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesSliceDeleteAll)
	t.Run("UserTables", testUserTablesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesExists)
	t.Run("UserTables", testUserTablesExists)
}

func TestFind(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesFind)
	t.Run("UserTables", testUserTablesFind)
}

func TestBind(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesBind)
	t.Run("UserTables", testUserTablesBind)
}

func TestOne(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesOne)
	t.Run("UserTables", testUserTablesOne)
}

func TestAll(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesAll)
	t.Run("UserTables", testUserTablesAll)
}

func TestCount(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesCount)
	t.Run("UserTables", testUserTablesCount)
}

func TestHooks(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesHooks)
	t.Run("UserTables", testUserTablesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesInsert)
	t.Run("UserMapTables", testUserMapTablesInsertWhitelist)
	t.Run("UserTables", testUserTablesInsert)
	t.Run("UserTables", testUserTablesInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("UserMapTableToUserTableUsingUser", testUserMapTableToOneUserTableUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("UserTableToUserUserMapTables", testUserTableToManyUserUserMapTables)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("UserMapTableToUserTableUsingUserUserMapTables", testUserMapTableToOneSetOpUserTableUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("UserTableToUserUserMapTables", testUserTableToManyAddOpUserUserMapTables)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesReload)
	t.Run("UserTables", testUserTablesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesReloadAll)
	t.Run("UserTables", testUserTablesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesSelect)
	t.Run("UserTables", testUserTablesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesUpdate)
	t.Run("UserTables", testUserTablesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("UserMapTables", testUserMapTablesSliceUpdateAll)
	t.Run("UserTables", testUserTablesSliceUpdateAll)
}
