// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserTables(t *testing.T) {
	t.Parallel()

	query := UserTables()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserTablesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserTablesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserTables().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserTablesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserTableSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserTablesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserTableExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserTable exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserTableExists to return true, but got false.")
	}
}

func testUserTablesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userTableFound, err := FindUserTable(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userTableFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserTablesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserTables().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserTablesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserTables().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserTablesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userTableOne := &UserTable{}
	userTableTwo := &UserTable{}
	if err = randomize.Struct(seed, userTableOne, userTableDBTypes, false, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}
	if err = randomize.Struct(seed, userTableTwo, userTableDBTypes, false, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userTableOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userTableTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserTables().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserTablesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userTableOne := &UserTable{}
	userTableTwo := &UserTable{}
	if err = randomize.Struct(seed, userTableOne, userTableDBTypes, false, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}
	if err = randomize.Struct(seed, userTableTwo, userTableDBTypes, false, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userTableOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userTableTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userTableBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func userTableAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTable) error {
	*o = UserTable{}
	return nil
}

func testUserTablesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserTable{}
	o := &UserTable{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userTableDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserTable object: %s", err)
	}

	AddUserTableHook(boil.BeforeInsertHook, userTableBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userTableBeforeInsertHooks = []UserTableHook{}

	AddUserTableHook(boil.AfterInsertHook, userTableAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userTableAfterInsertHooks = []UserTableHook{}

	AddUserTableHook(boil.AfterSelectHook, userTableAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userTableAfterSelectHooks = []UserTableHook{}

	AddUserTableHook(boil.BeforeUpdateHook, userTableBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userTableBeforeUpdateHooks = []UserTableHook{}

	AddUserTableHook(boil.AfterUpdateHook, userTableAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userTableAfterUpdateHooks = []UserTableHook{}

	AddUserTableHook(boil.BeforeDeleteHook, userTableBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userTableBeforeDeleteHooks = []UserTableHook{}

	AddUserTableHook(boil.AfterDeleteHook, userTableAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userTableAfterDeleteHooks = []UserTableHook{}

	AddUserTableHook(boil.BeforeUpsertHook, userTableBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userTableBeforeUpsertHooks = []UserTableHook{}

	AddUserTableHook(boil.AfterUpsertHook, userTableAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userTableAfterUpsertHooks = []UserTableHook{}
}

func testUserTablesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserTablesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userTableColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserTableToManyUserUserMapTables(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserTable
	var b, c UserMapTable

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, userMapTableDBTypes, false, userMapTableColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userMapTableDBTypes, false, userMapTableColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.UserID = a.ID
	c.UserID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.UserUserMapTables().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.UserID == b.UserID {
			bFound = true
		}
		if v.UserID == c.UserID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := UserTableSlice{&a}
	if err = a.L.LoadUserUserMapTables(ctx, tx, false, (*[]*UserTable)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.UserUserMapTables); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.UserUserMapTables = nil
	if err = a.L.LoadUserUserMapTables(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.UserUserMapTables); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testUserTableToManyAddOpUserUserMapTables(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserTable
	var b, c, d, e UserMapTable

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userTableDBTypes, false, strmangle.SetComplement(userTablePrimaryKeyColumns, userTableColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UserMapTable{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userMapTableDBTypes, false, strmangle.SetComplement(userMapTablePrimaryKeyColumns, userMapTableColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*UserMapTable{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddUserUserMapTables(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.UserID {
			t.Error("foreign key was wrong value", a.ID, first.UserID)
		}
		if a.ID != second.UserID {
			t.Error("foreign key was wrong value", a.ID, second.UserID)
		}

		if first.R.User != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.User != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.UserUserMapTables[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.UserUserMapTables[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.UserUserMapTables().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testUserTablesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserTablesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserTableSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserTablesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserTables().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userTableDBTypes = map[string]string{`ID`: `integer`, `Handle`: `character varying`, `Email`: `character varying`, `FirstName`: `character varying`, `LastName`: `character varying`, `IsVerified`: `boolean`}
	_                = bytes.MinRead
)

func testUserTablesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userTablePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userTableAllColumns) == len(userTablePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTablePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserTablesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userTableAllColumns) == len(userTablePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserTable{}
	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userTableDBTypes, true, userTablePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userTableAllColumns, userTablePrimaryKeyColumns) {
		fields = userTableAllColumns
	} else {
		fields = strmangle.SetComplement(
			userTableAllColumns,
			userTablePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserTableSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserTablesUpsert(t *testing.T) {
	t.Parallel()

	if len(userTableAllColumns) == len(userTablePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserTable{}
	if err = randomize.Struct(seed, &o, userTableDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserTable: %s", err)
	}

	count, err := UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userTableDBTypes, false, userTablePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserTable struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserTable: %s", err)
	}

	count, err = UserTables().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
