/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-02-23 23:03:54 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/postgres -t user_table -s public
 *
 */


export namespace user_tableFields {
    export type id = number;
    export type handle = string;
    export type email = string;
    export type first_name = string;
    export type last_name = string;
    export type is_verified = boolean;

}

export interface user_table {
    id: user_tableFields.id;
    handle: user_tableFields.handle;
    email: user_tableFields.email;
    first_name: user_tableFields.first_name;
    last_name: user_tableFields.last_name;
    is_verified: user_tableFields.is_verified;

}
